### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms#1410]
### Features

* For now, support only NL and EN.
* Offer terminology source metadata in both languages.
* Filter by language dynamically (instead of hardcoded NL, as it is now).

### Overview of sources

Which sources support multiple languages?

* AAT: NL, EN, ES, FR, ZH
* Eurovoc: [many languages](http://publications.europa.eu/resource/authority/eurovoc/3039)
* RKD: NL, EN
* Uitvoeringsmedium: DE, EN, ES, FR, IT, NL
* Wikidata: many languages

All other sources are NL only, except Iconclass, which is EN only.

### Tasks

* [x] Extend the catalog with EN metadata.
* [x] For the sources GraphQL endpoint, return both NL and EN; clients can then filter by language. Do we want `name_nl`, `name_en` or rather `name` as an object with `language` and `value` properties for more flexibility? Clients can then filter. Try to keep BC here.
* [x] If the demonstrator’s language is EN, show catalog in EN.
* [x] #1476
* [x] On https://termennetwerk.netwerkdigitaalerfgoed.nl/sources, show the supported languages for each source.
* [x] Parameterise the GraphQL terms query with a property `languages` which takes an array of preferred search/result languages: e.g. `[nl]`, `[nl, en]`.
* [x] Parameterise the lookup query with `languages`.
* [x] Return the language of each result in the terms query endpoint. Clients can then either show all results, hide non-preferred languages or optionally show them.

**Comment by ddeboer** [comment]
We could add `prefLabels, altLabels, ...` alongside `prefLabel, altLabel, ...`. The new plurals would then contain a list of objects: `[{language: 'en', value: 'Some literal value'}, {language ...}]`.

Do we like this approach?
Upside: full backwards compatibility.
Downside: looks less like skos, which uses singular `prefLabel` etc.

A remaining question is how in our SPARQL queries we can translate language-tagged literals to this object structure. Can we even access a literal’s language?

**Comment by coret** [comment]
> We could add `prefLabels, altLabels, ...` alongside `prefLabel, altLabel, ....`

This seem to be a solution outside of SKOS (purals not defined in https://www.w3.org/2009/08/skos-reference/skos.html)? It would be something like `nde:PrefLabels` and `nde:altLabels`?

**Comment by EnnoMeijers** [comment]
Could the SKOS-XL approach be helpful to model the GraphQL output? This seems to be relevant for multi lingual support, B&G uses SKOS-XL for GTAA source. If not, I am ok with the proposed approach, no need for prefixes indeed.

**Comment by ddeboer** [comment]
Also supported on http://termennetwerk.netwerkdigitaalerfgoed.nl: try the language toggle when viewing results from a multilingual terminology source. Documentation will follow.
