### ISSUE TITLE
SPARQL API

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms#922]
The Network of Terms offers a GraphQL API, Reconciliation API and CLI access. This works well for finding terms for existing data in collection management systems, which are expected to store the URIs of the terms.

However, URIs by themselves are rarely useful, neither in the collection management system nor any end-user services built on top of them. Joining `prefLabel` and other SKOS metadata to the labels is possible through the [GraphQL lookup call](https://github.com/netwerk-digitaal-erfgoed/network-of-terms/tree/master/packages/network-of-terms-graphql#look-up-terms-by-uri), but that requires a client implementation. LD-savvy users may want to rely on just SPARQL instead.

The addition of a SPARQL API solves this problem. It could work similarly to [Wikidata’s label service](https://en.wikibooks.org/wiki/SPARQL/SERVICE_-_Label).

### Tasks

- [ ] Parse the client’s SPARQL query to SPARQL algebra.
- [ ] Convert that algebra to a function call of the existing lookup functionality: `lookup(iri: IRI[])`.
- [ ] Serialise the results to SPARQL and return them to the client.

/cc @coret @EnnoMeijers

**Comment by ddeboer** [comment]
@rlzijdeman is asking for a SPARQL endpoint. We decided to investigate what the needs are before deciding to implement this.

**Comment by ddeboer** [comment]
Not needed for that use case, nor any other use cases known, so closing for now.
